### ISSUE TITLE
楽曲の検索結果画面の実装

### ISSUE THREAD

**Issue by txxxxc** [lit-kansai/dj-system-front#195]
# 概要
楽曲の検索結果画面の実装

## タスク

- [ ]  楽曲検索のAPIつなぎこむ
- [ ] モーダルを開く
- [ ] 楽曲リクエストAPIをつなぎこむ

## 補足

pages/room/[id]/search-result.vueに作る

## 参考リンク
[figma](https://www.figma.com/file/ARpMulqQgkx4kdPyFvgde1/DJ-team-library?node-id=0%3A1&t=HjPVzWp5kgu5ro0h-0)

![image](https://user-images.githubusercontent.com/22112440/224618536-8624f536-5ac4-47b4-bd2d-7877af0779d8.png)

![image](https://user-images.githubusercontent.com/22112440/224618829-5196958b-20e0-49d6-84a7-51613b36eaed.png)

**Comment by txxxxc** [comment]
モーダルまだなんで一旦曲の検索機能だけでOKです

**Comment by penguin4731** [comment]
srcのcomponentsにmusic-cardを移動させてからする
