### ISSUE TITLE
ナビゲーションバーの挙動

### ISSUE THREAD

**Issue by txxxxc** [lit-kansai/dj-system-front#211]
# 概要

> ナビゲーションバーのinputの挙動めっちゃむずそう。
/:room_id/searchのときはこれで良いんだけど、/:room_idのときはqueryがpushされても挙動に変化が無いので別の動きをしてほしい説がある

## タスク

- [ ] 細かいタスクに分解できているなら書き出す

## 参考リンク

Figmaのリンクなど

**Comment by penguin4731** [comment]
一旦解決できたのでClose
