### ISSUE TITLE
Admin側の動作確認

### ISSUE THREAD

**Issue by txxxxc** [lit-kansai/dj-system-front#288]
# 概要
ある程度実装は完成してるので一通り確認お願いしたいです！！

## タスク

- [ ] 細かいタスクに分解できているなら書き出す

## 参考リンク

Figmaのリンクなど

**Comment by gassi4731** [comment]
- [ ]  ログイン周り
  - [ ]  Googleログインができる
  - [ ]  ログアウトができる
  - [ ]  ログインのセッションが切れたときに、ログイン画面に戻る
- [ ]  ルーム周り
  - [ ]   ルーム作成できる
  - [ ]  ルームの情報が表示できる（音楽・メッセージ）
  - [ ]  ルームの情報が編集できる
- [ ] ユーザー周り
  - [ ] Spotifyと連携できる

**Comment by gassi4731** [comment]
- ルーム作成失敗した時に、ログアウトされる
- ルーム詳細（メモ）をマストでいれる必要がある
