### ISSUE TITLE
レスポンシブ崩れてるところ直す

### ISSUE THREAD

**Issue by txxxxc** [lit-kansai/dj-system-front#313]
# 概要

レスポンシブ崩れてる部分良い感じに直したい

## タスク

- [ ] 細かいタスクに分解できているなら書き出す

## 参考リンク

Figmaのリンクなど

**Comment by gassi4731** [comment]
/:room_id
- Auto focusが、上の検索バーにあたってしまっている

/:room_id/search
- モーダル内で、1073px以下のときに「リクエストを送信」ボタンのデザインが崩れる
